# Generated by Django 3.1.3 on 2020-11-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0002_post_num_beam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
